source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

workspace 'WeatherWorkspace.xcworkspace'

def import_pods
  pod 'AFNetworking', '~> 3.0'
end

target 'Weather' do
    project './Weather/Weather.xcodeproj'
    import_pods
end

target 'WeatherCore' do
    project './WeatherCore/WeatherCore.xcodeproj'
    import_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
        end
    end
end
